---
title: "GC5"
author: "Phineas Pham"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: true
      base_font:
        google: EB Garamond
  word_document:
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=F, warning = F)


library(ggrepel)
library(tidyverse)
library(googlesheets4)
library(car)
library(scales)
library(ggridges)
#library(remotes)
#remotes::install_github("ryanburge/socsci")
library(socsci)
library(paletteer)
library(peacesciencer)

theme_djupe <- function() {
  theme_minimal() %+replace%
  theme(text=element_text(family="G", size=12),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom",
        plot.title.position = "plot")
}

#Building the dataset from the peacesciencer package
rm(dem)
dem <- create_stateyears() %>% add_democracy() 

#putting polity on a 0-1 scale
dem <- dem %>% mutate(polity2c=(polity2+10)/20)

#figuring out how many are experiencing backsliding through lagging
dem <- dem %>% mutate(vdlag=lag(v2x_polyarchy),
                      backsliding=v2x_polyarchy-vdlag,
                      backslidingc=case_when(backsliding<0 ~ "Backsliding",
                                             backsliding>=0 ~ "Not sliding"))

#Recoding polity into three groups: autocracy=0, anocracy=1, democracy=2
dem <- dem %>% mutate(p3=car::recode(polity2,"-10:-5.1=0;
                                     -5:5=1; 
                                     5.1:10=2"))
gs4_deauth()
vdemcorr <- range_speedread("https://docs.google.com/spreadsheets/d/1DRCEa4ygKAZ6ASfeNrPFHQEwfodbBA3YysNE2srx-wE/edit?usp=sharing")

library(countrycode)
dem <- dem %>% mutate(iso3c=countrycode(ccode, origin="cown", destination="iso3c"))

dem <- left_join(dem, vdemcorr, by="iso3c")

dem <- dem[!is.na(dem$region),]


```

```{r}
dem1 <- dem %>%
  group_by(year.x, region) %>% mean_ci(v2x_polyarchy)
```

```{r}
dem2 <- filter(dem1, year.x >= 1950 & year.x <= 2019)
dem2
```


```{r}
data_ends <- dem2 %>% filter(year.x == 2019)
data_fronts <- dem2 %>% filter(year.x == 1950)
data_ends
```


```{r}
dem2 %>% 
  ggplot(aes(x= year.x, y=mean, color=region)) +
  geom_line() +
  #geom_text_repel(aes(label=region))+
  geom_text_repel(
    aes(label = mean), data = data_ends,
    fontface ="plain", family= "G", position = "identity"
    )+
  geom_text_repel(
    aes(label = mean), data = data_fronts,
    fontface ="plain", family= "G"
    )+
  
#  xlim(1940,2020) + 
#  ylim(0.2, 0.8) +
  scale_x_continuous(breaks=seq(1950, 2020, 10))+
  scale_y_continuous(breaks=seq(0.1, 0.9, 0.2))+
  labs(x="", y="Polyarchy Score", 
       title = "Regional Democratic Development is Uneven, 1950-2019",
       caption = "Source: Varieties of Democracy Project. @PhineasPham")+
  theme_minimal()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title.position = "plot",
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```








